 export const profissoes = [
    'Especialista FP&A',
    'Assistente Comercial JR',
    'Gerente de Exportação',
    'Gerente de Supply Chain',
    'Head de RH',
    'Contador (a)',
    'Corretor de Seguros',
    'COML 01 - Vendedor JR / PL / SR',
    '#1 - Desenvolvedor Mobile Android',
    '#2 - Desenvolvedor Mobile IOS',
    '#3 - Qualidade Software Automatizador',
    '#4 - Qualidade Software Analista Testes',
    '#5 - DevOps',
    '#6 - Desenvolvedor Phyton',
    '#7 - Desenvolvedor Java',
    '#8 - Desenvolvedor Back-end (CLT-SP)',
    '#9 - Desenvolvedor Back-end (PJ Remoto)',
    '#10 - Desenvolvedor Android (Java e Kotlin)',
    '#11 - Eng° Teste de Automação (C#, .Net e Selenium)',
    '#12 - Eng° de Software Back-end .NET',
    '#13 - Desenvolvedor Back-end Java',
    '#14 - Eng° Software Back-end Java',
    '#15 - Eng° DevOps',
    '#16 - Desenvolvedor Front-End de Web e Mobile React',
    '#17 - Engº de software Front-End',
    '#18 - Engº de Automação de Teste de Front-End',
    '#19 - Recrutador de TI',
    '#20 - Desenvolvedor Mobile',
    '#21 - Engº Automação de Teste Móvel',
    '#22 - React Native Developer',
    '#23 - Engº Automação de Teste',
    '#24 - Desenvolvedor IOS​',
    '#25 - Líder de desenvolvimento de negócios- Mercado dos EUA',
    '#26 - Líder global de educação',
    'Assistente',
    '#27-Recrutador de TI',
    '#28 - PMO JR - PJ',
    '#29 - Consultor Técnico Mastersaf DW PJ',
    '#30 - RD 001 - Analista Suporte Pinhais / PR',
    '#31 - RD 002 - Analista Suporte PJ',
    '#32- RD 003 - Desenvolvedor JAVA Front-End',
    '#33- RD 004 - Scrum Master',
    '#34- ALZ 001 - Desenvolvedor JAVA Back-End PL PJ',
    '#35 - FJK 001 - Arquiteto Software PJ',
    '#36 - BBCE - Desenvolvedor Back-End Node.Js PJ',
    '#37 - FJK 002 - Desenvolvedor JAVA Front-End PJ',
    '#38 - Desenvolvedor Front-End React SR PJ',
    '#39 - Tech Lead JAVA PJ',
    '#40 - Desenvolvedor Java Back-End Sr',
    '#41 - Analista de Sistemas',
    '#42 - Desenvolvedor JAVA Back-End Senior (Farma)',
    '#43 - Desenvolvedor Back-End Java Senior  (Banco)',
    'Advogado (a)',
    'Contador',
    'Analista',
    'Coordenação ou Supervisão',
    'M01 - Coordenador de Mídia e Performance',
    'M02 - Coordenador de Conteúdo',
    'M03 - Coordenador de Mídias Sociais',
    'M04 - Coordenador de Designer',
    'C-01 - Coordenador de Vendas B2B',
    'Gerência',
    'Diretoria',
    'I01 - Diretor Geral de Gestão e Operações',
    'Presidência',
    'Outros',
    'Barista',
    'Atendente de balcão',
    'Cozinheiro',
    'Auxiliar de Cozinha',
    'Caixa',
    'Gerente Administrativo',
    'Analista Comercial e de Licitações',
    'Analista Comercial (BI)',
    'Analista de CRM',
    'Projetista Mecânico',
    'Eletricista - Técnico de Manutenção',
    'Gestor de Tráfego',
    'Vendedor Técnico',




];